name: Check Redirects
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  check_redirects:
    runs-on: ubuntu-latest
    name: Check Redirects Job
    timeout-minutes: 60
    steps:
      - name: Check Redirects
        uses: steadybit/gitbook-redirect-checker@v0.1
        if: "!cancelled()"

      - name: Notify Slack channel
        uses: 8398a7/action-slack@v3
        with:
          channel: '#test-experiments-dev'
          status: ${{ job.status }}
          text: Found broken redirects in docs
          fields: workflow,action
          author_name: github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure()
